server.port=8080
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:alertify}
spring.datasource.username=${DB_USER:alertify}
spring.datasource.password=${DB_PASSWORD:alertify}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
